image: Ubuntu1804

branches:
  only:
    - master

build: off

build_script:
  - ps: sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  - ps: sudo chmod +x /usr/local/bin/docker-compose
  - ps: sudo docker-compose up -d

test_script:
  - ps: ./gradlew test --info "-Dselenide.headless=true"